fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs-stdlib"
      ref: "4.14.0"
    ntp:
      repo: "puppetlabs-ntp"
      ref: "6.0.0"
    sysctl:
      repo: "thias-sysctl"
      ref: "1.0.6"
    motd:
      repo: "puppetlabs-motd"
      ref: "1.4.0"
    hiera:
      repo: "puppet-hiera"
      ref: "2.3.0"
    inifile:
      repo: 'puppetlabs-inifile'
      ref: '1.6.0'
    vcsrepo:
      repo: 'puppetlabs-vcsrepo'
      ref: '1.5.0'
    firewall:
      repo: 'puppetlabs-firewall'
      ref: '1.8.1'
  repositories:
    psquared: "https://github.com/geoffwilliams/psquared.git"
    pe_repo: "https://github.com/GeoffWilliams/geoffwilliams-pe_repo"
    nagios: "https://github.com/GeoffWilliams/puppet-nagios"
  symlinks:
    r_profile: "#{source_dir}"
