fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs-stdlib"
      ref: "4.13.1"
    ntp:
      repo: "puppetlabs-ntp"
      ref: "6.0.0"
    sysctl:
      repo: "thias-sysctl"
      ref: "1.0.6"
    motd:
      repo: "puppetlabs-motd"
      ref: "1.4.0"

  symlinks:
    r_profile: "#{source_dir}"
